title: HEXAGONAL DIGITAL SURFACE MODEL
description: Using Icosahedral-based Geodesic Discrete Global Grid To Build Hexagonal Digital Surface Model
show_downloads: False
google_analytics:
theme: jekyll-theme-hacker
