title: HEXAGONAL DIGITAL SURFACE MODEL
description: Using icosahedral-based geodesic discrete global grid to build hexagonal digital surface model
show_downloads: False
google_analytics:
theme: jekyll-theme-hacker
